---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install git+git://github.com/ansible/ansible.git@v2.1.1.0-0.1.rc1

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Test for Syntax
  - >
    ansible-playbook -i tests/inventory tests/test.yml
    --syntax-check
  # Test for Failure
  - >
    ansible-playbook -i tests/inventory tests/test.yml --become
    --connection=local
  # Test for Idempotence
  - >
    ansible-playbook -i tests/inventory tests/test.yml --become
    --connection=local
    | grep -q 'changed=0.*failed=0'
  # Test for Succuss
  - >
    service autodl-irssi status
    | grep -q "running"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
