---
# tasks file for ansible-autodl-irssi

- name: Load service manager variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_service_mgr }}.yml"
    - default.yml

- name: Install ansible dependancies
  package:
    name: "{{ item }}"
  with_items:
    - cpanminus
  tags:
    - dependencies

- name: Install cpan dependancies
  package:
    name: "{{ item }}"
  with_items:
    - gcc
    - make
    - libssl-dev
    - libxml2-dev
  tags:
    - dependencies

- name: Install autodl-irssi dependancies
  cpanm:
    name: "{{ item }}"
  with_items:
    - Archive::Zip
    - Net::SSLeay
    - HTML::Entities
    - XML::LibXML
    - Digest::SHA
    - JSON
    - JSON::XS
  tags:
    - dependencies

- name: Unpack source into scripts directory
  unarchive:
    src: "{{ autodl_irssi_download_url }}"
    dest: "{{ irssi_directory_scripts }}"
    copy: no
    creates: "{{ irssi_directory_scripts }}/AutodlIrssi"
    owner: "{{ rtorrent_user }}"
    group: "{{ rtorrent_group }}"
  tags:
    - install

- name: Install autodl-irssi in autorun folder
  file:
    src: "{{ irssi_directory_scripts }}/autodl-irssi.pl"
    dest: "{{ irssi_directory_autorun }}/autodl-irssi.pl"
    state: link
  tags:
    - install

- name: Create autodl-irssi config directory
  file:
    path: "{{ autodl_irssi_directory_config }}"
    state: directory
    owner: "{{ rtorrent_user }}"
    group: "{{ rtorrent_group }}"
  tags:
    - configuration

- name: Configure autodl-irssi
  template:
    src: autodl.cfg.j2
    dest: "{{ autodl_irssi_directory_config }}/autodl.cfg"
    owner: "{{ rtorrent_user }}"
    group: "{{ rtorrent_group }}"
  tags:
    - configuration

- include_tasks: rutorrent_plugin.yml
  when:
    - autodl_irssi_configure_rutorrent_plugin

- name: Install tmux
  package:
    name: tmux
    state: present
  tags:
    - service

- name: Create autodl-irssi service
  template:
    src: "{{ autodl_irssi_service_filename }}"
    dest: "{{ autodl_irssi_service_destination }}"
    owner: root
    group: root
    mode: "{{ autodl_irssi_service_mode }}"
  notify:
    - Restart autodl-irssi
  tags:
    - service

- name: Ensure autodl-irssi service is started
  service:
    name: autodl-irssi
    state: started
    enabled: yes
  tags:
    - service

- name: Add sudoers file
  template:
    src: autodl-irssi.j2
    dest: /etc/sudoers.d/autodl-irssi
    owner: root
    group: root
    mode: 0440
  tags:
    - service

- name: Add connection script
  template:
    src: connect-autodl-irssi.j2
    dest: /usr/local/sbin/connect-autodl-irssi
    owner: root
    group: root
    mode: a+x
  tags:
    - service
