---
# tasks file for ansible-autodl-irssi rutorrent_plugin

- name: Load a variable file based on the OS type, or a default if not found.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: Install autodl-irssi rutorrent plugin dependencies
  package:
    name: "{{ item }}"
  notify:
    - Restart apache
  with_items: "{{ autodl_irssi_plugin_dependencies }}"
  tags:
    - dependancies

- name: Unpack source into plugin directory
  unarchive:
    src: "{{ autodl_irssi_rutorrent_plugin_download_url }}"
    dest: "{{ autodl_irssi_rutorrent_plugin_directory }}"
    copy: no
    creates: "{{ autodl_irssi_rutorrent_plugin_directory }}/autodl-irssi"
    group: www-data
    mode: g+w
  tags:
    - install

- name: Rename unpacked folder
  command: mv {{ autodl_irssi_rutorrent_plugin_directory }}/autodl-rutorrent-community-{{ autodl_irssi_rutorrent_plugin_version }} {{ autodl_irssi_rutorrent_plugin_directory }}/autodl-irssi
  args:
    creates: "{{ autodl_irssi_rutorrent_plugin_directory }}/autodl-irssi"
  tags:
    - install

- name: Configure autodl-irssi rutorrent plugin
  template:
    src: conf.php.j2
    dest: "{{ autodl_irssi_rutorrent_plugin_directory }}/autodl-irssi/conf.php"
    group: www-data
    mode: g+w
  notify:
    - Restart apache
  tags:
    - configuration
